[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Flow Labs Metric Documentation"
authors = [{name = "Flow Labs", email = "team@flowlabs.ai"}]
dynamic = ["version", "description"]
